/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2025 Oplus. All rights reserved.
 */
#ifndef __OPLUS_FEATURE_CPU_IPS_TABLE_CHIP_H__
#define __OPLUS_FEATURE_CPU_IPS_TABLE_CHIP_H__

#include <linux/types.h>

/* magic code get from benchmark test */
#define IPS_CLUSTER0_MIN_TEST_BASE_CPI 177273
#define IPS_CLUSTER1_MIN_TEST_BASE_CPI 176185
/* cluster2 */
#define IPS_CLUSTER2_MIN_TEST_BASE_CPI 176185

/* cluster0 config */
#define IPS_CLUSTER0_MAX_MEM_STALL 2500
#define IPS_CLUSTER0_MIN_MEM_STALL 0
#define IPS_CLUSTER0_MEM_STALL_STEP 100
/* base_cpi multiply 1000000 */
#define IPS_CLUSTER0_MAX_BASE_CPI 2500000
#define IPS_CLUSTER0_MIN_BASE_CPI 200000
#define IPS_CLUSTER0_BASE_CPI_STEP 100000

#define IPS_CLUSTER0_FREQ_NUM 12
#define IPS_CLUSTER0_BASE_CPI_NUM 23
#define IPS_CLUSTER0_MEM_STALL_NUM 25
#define IPS_CLUSTER0_BASE_CPI_MIN_IDX 0
#define IPS_CLUSTER0_BASE_CPI_MAX_IDX 22
#define IPS_CLUSTER0_MEM_STALL_MIN_IDX 0
#define IPS_CLUSTER0_MEM_STALL_MAX_IDX 24


/* cluster1 config */
/*
 * cluster1 base_CPI  num = 23
 * cluster1 mem_stall num = 25
 * cluster1 freq num = 14
 */
#define IPS_CLUSTER1_MAX_MEM_STALL 2500
#define IPS_CLUSTER1_MIN_MEM_STALL 0
#define IPS_CLUSTER1_MEM_STALL_STEP 100
/* base_cpi multiply 1000000 */
#define IPS_CLUSTER1_MAX_BASE_CPI 2500000
#define IPS_CLUSTER1_MIN_BASE_CPI 200000
#define IPS_CLUSTER1_BASE_CPI_STEP 100000

#define IPS_CLUSTER1_FREQ_NUM 14
#define IPS_CLUSTER1_BASE_CPI_NUM 23
#define IPS_CLUSTER1_MEM_STALL_NUM 25
#define IPS_CLUSTER1_BASE_CPI_MIN_IDX 0
#define IPS_CLUSTER1_BASE_CPI_MAX_IDX 22
#define IPS_CLUSTER1_MEM_STALL_MIN_IDX 0
#define IPS_CLUSTER1_MEM_STALL_MAX_IDX 24



#define IPS_CLUSTER2_MAX_MEM_STALL 2500
#define IPS_CLUSTER2_MIN_MEM_STALL 0
#define IPS_CLUSTER2_MEM_STALL_STEP 100
/* base_cpi multiply 1000000 */
#define IPS_CLUSTER2_MAX_BASE_CPI 2500000
#define IPS_CLUSTER2_MIN_BASE_CPI 200000
#define IPS_CLUSTER2_BASE_CPI_STEP 100000

#define IPS_CLUSTER2_FREQ_NUM 14
#define IPS_CLUSTER2_BASE_CPI_NUM 23
#define IPS_CLUSTER2_MEM_STALL_NUM 25
#define IPS_CLUSTER2_BASE_CPI_MIN_IDX 0
#define IPS_CLUSTER2_BASE_CPI_MAX_IDX 22
#define IPS_CLUSTER2_MEM_STALL_MIN_IDX 0
#define IPS_CLUSTER2_MEM_STALL_MAX_IDX 24

#endif
